apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: ttapp
  name: tt-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      run: ttapp
  template:
    metadata:
       annotations:
         date: "{{DATE}}"
       labels:
        run: ttapp
    spec:
      containers:
      - image: eu.gcr.io/tt-jenkins/ttdocker:{{IMAGETAG}}
        imagePullPolicy: Always
        name: ttapp
        resources: {}
