apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: ttapp
  name: tt-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      run: ttapp
  template:
    metadata:
       labels:
        run: ttapp
    spec:
      containers:
        image: eu.gcr.io/tt-jenkins/ttdocker:R1.0
        name: ttapp
        resources: {}
